## blackmatrix7 仓库自动定时同步代码

## 每24小时时拉取一次作者脚本到自己仓库的分支



name: blackmatrix7-sync
on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-blackmatrix7-ios_rule_script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync blackmatrix7-ios_rule_script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/blackmatrix7/ios_rule_script.git"
          source_branch: "master"
          destination_branch: "blackmatrix7"
          github_token: ${{ secrets.PAT }}
